name: Server
main: de.flaflo.main.Main
version: 1.6
depend: [WorldEdit]
commands:
   ping:
      description: Eigenen Ping auslesen
      command: /ping
   fly:
      description: Fliegen (an/aus)
      command: /fly
   spawn:
      description: Zum Spawn teleportieren
      command: /spawn
   damage:
      description: Schaden (an/aus)
      command: /damage
   heal:
      description: Füllt alle Stats auf ihr maximum
      command: /heal
   apple:
      description: Gibt dir einen/mehrere OP-Äpfel
      command: /heal
   warp:
      description: Teleportiert zu einem Warp-Punkt
      command: /warp
   tpa:
      description: Teleportiert zu andere Spieler
      command: /tpa
   c:
      description: Virtuell einen Server Command senden
      command: /c
   hunger:
      description: Hunger (an/aus)
      command: /hunger
   afk:
      description: AFK-Modus wechseln
      command: /afk
   item:
      description: Gibt dir allerlei Items
      command: /item
   clear:
      description: Leert das Inventar
      command: /clear
   freebuild:
      description: Freebuild Befehle
      command: /freebuild
   mute:
      description: Spieler ent/muten
      command: /mute
   whois:
      description: Spieler stats
      command: /whois <player>